version: '3.8'
services:
  web:
    build:
      context: .
    command: ['npm', 'run', 'build']
    environment:
      - 'REACT_APP_CHAIN_ID=${REACT_APP_CHAIN_ID}'
      - 'REACT_APP_CHAIN_NAME=${REACT_APP_CHAIN_NAME}'
      - 'REACT_APP_LCD_URL=${REACT_APP_LCD_URL}'
      - 'REACT_APP_RPC_URL=${REACT_APP_RPC_URL}'
      - 'REACT_APP_CONTRACT=${REACT_APP_CONTRACT}'
    volumes:
      - './build/:/app/build'
